class CommandAlreadyExists(Exception):
    pass

class CommandError(Exception):
    pass